import streamlit as st
from groq import Groq
import os
from dotenv import load_dotenv
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER
import io

# ── Load env ──────────────────────────────────────────────────────────────────
load_dotenv()

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="SOPilot — AI SOP Generator",
    page_icon="📋",
    layout="centered"
)

# ── Custom CSS ────────────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600&family=DM+Mono:wght@400;500&display=swap');

html, body, [class*="css"] {
    font-family: 'DM Sans', sans-serif;
}

.sop-header {
    background: linear-gradient(135deg, #0f172a 0%, #1e3a5f 100%);
    border-radius: 16px;
    padding: 2rem 2.5rem;
    margin-bottom: 2rem;
    border: 1px solid #334155;
}
.sop-header h1 {
    color: #f8fafc;
    font-size: 2rem;
    font-weight: 600;
    margin: 0 0 0.3rem 0;
    letter-spacing: -0.5px;
}
.sop-header p {
    color: #94a3b8;
    font-size: 0.95rem;
    margin: 0;
}
.sop-badge {
    display: inline-block;
    background: #1d4ed8;
    color: #bfdbfe;
    font-size: 0.7rem;
    font-weight: 600;
    letter-spacing: 1.5px;
    text-transform: uppercase;
    padding: 3px 10px;
    border-radius: 20px;
    margin-bottom: 0.8rem;
}
.section-label {
    font-size: 0.75rem;
    font-weight: 600;
    letter-spacing: 1.2px;
    text-transform: uppercase;
    color: #64748b;
    margin-bottom: 0.4rem;
}
.sop-output {
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-left: 4px solid #1d4ed8;
    border-radius: 10px;
    padding: 1.8rem 2rem;
    font-family: 'DM Sans', sans-serif;
    font-size: 0.92rem;
    line-height: 1.75;
    color: #1e293b;
    white-space: pre-wrap;
    margin: 1.5rem 0;
}
.status-done {
    background: #dcfce7;
    color: #166534;
    border: 1px solid #bbf7d0;
    border-radius: 8px;
    padding: 0.6rem 1rem;
    font-size: 0.85rem;
    font-weight: 500;
}
#MainMenu {visibility: hidden;}
footer {visibility: hidden;}
.stDeployButton {visibility: hidden;}
</style>
""", unsafe_allow_html=True)


# ── Helper: Build Prompt ───────────────────────────────────────────────────────
def build_prompt(process_description: str, department: str, complexity: str, refinement: str = "") -> str:
    complexity_instruction = (
        "Generate a concise, single-page SOP. Keep each section brief and to the point."
        if complexity == "Simple"
        else "Generate a detailed, comprehensive SOP. Each section should be thorough with specific steps, sub-steps where needed, and clear ownership."
    )

    refinement_instruction = (
        f"\n\nIMPORTANT REFINEMENT REQUEST: {refinement}\nApply this refinement to the SOP you generate."
        if refinement else ""
    )

    return f"""You are an expert Business Process Analyst. Generate a professional Standard Operating Procedure (SOP) document.

PROCESS DESCRIPTION:
{process_description}

DEPARTMENT CONTEXT: {department}
COMPLEXITY LEVEL: {complexity}
{complexity_instruction}
{refinement_instruction}

Generate the SOP in this EXACT format with these EXACT section headers:

TITLE: [Clear, action-oriented SOP title]

PURPOSE
[Why this SOP exists and what it achieves]

SCOPE
[Who this applies to and what it covers / excludes]

ROLES & RESPONSIBILITIES
[List each role and their specific responsibility in this process]

PRE-REQUISITES
[What must be in place before starting this process]

STEP-BY-STEP PROCEDURE
[Numbered steps. Be specific. Include decision points where relevant.]

EDGE CASES & EXCEPTIONS
[What to do when things don't go as planned]

SUCCESS METRICS
[How to measure if this process is being followed correctly and delivering results]

---
Generated by SOPilot | {department} Department | {datetime.now().strftime("%B %d, %Y")}

Important: Use plain text only. No markdown symbols like **, ##, or *. Use clean numbered and lettered lists."""


# ── Helper: Generate PDF ───────────────────────────────────────────────────────
def generate_pdf(sop_text: str, title: str) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'SOPTitle', parent=styles['Normal'],
        fontSize=20, fontName='Helvetica-Bold',
        textColor=colors.HexColor('#0f172a'),
        spaceAfter=6, leading=26
    )
    meta_style = ParagraphStyle(
        'SOPMeta', parent=styles['Normal'],
        fontSize=9, fontName='Helvetica',
        textColor=colors.HexColor('#64748b'), spaceAfter=16
    )
    heading_style = ParagraphStyle(
        'SOPHeading', parent=styles['Normal'],
        fontSize=11, fontName='Helvetica-Bold',
        textColor=colors.HexColor('#1d4ed8'),
        spaceBefore=16, spaceAfter=6, leading=16
    )
    body_style = ParagraphStyle(
        'SOPBody', parent=styles['Normal'],
        fontSize=10, fontName='Helvetica',
        textColor=colors.HexColor('#1e293b'),
        spaceAfter=4, leading=16
    )
    footer_style = ParagraphStyle(
        'SOPFooter', parent=styles['Normal'],
        fontSize=8, fontName='Helvetica',
        textColor=colors.HexColor('#94a3b8'),
        alignment=TA_CENTER, spaceBefore=20
    )

    section_headers = [
        "PURPOSE", "SCOPE", "ROLES & RESPONSIBILITIES",
        "PRE-REQUISITES", "STEP-BY-STEP PROCEDURE",
        "EDGE CASES & EXCEPTIONS", "SUCCESS METRICS"
    ]

    story = []
    doc_title = title if title else "Standard Operating Procedure"
    story.append(Paragraph(doc_title, title_style))
    story.append(Paragraph(f"Generated on {datetime.now().strftime('%B %d, %Y')} · SOPilot AI", meta_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e2e8f0'), spaceAfter=12))

    for line in sop_text.strip().split('\n'):
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 4))
            continue
        if stripped.startswith("TITLE:"):
            continue
        if stripped.startswith("Generated by SOPilot"):
            story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e2e8f0'), spaceBefore=12, spaceAfter=8))
            story.append(Paragraph(stripped, footer_style))
            continue
        if stripped == "---":
            continue
        if any(stripped == h for h in section_headers):
            story.append(Paragraph(stripped, heading_style))
        else:
            safe = stripped.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            story.append(Paragraph(safe, body_style))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()


# ── Helper: Call Groq API ───────────────────────────────────────────────────
def call_gemini(prompt: str) -> str:
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        st.error("❌ GROQ_API_KEY not found. Check your .env file.")
        st.stop()
    client = Groq(api_key=api_key)
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content    



# ── Session State Init ────────────────────────────────────────────────────────
if "sop_output" not in st.session_state:
    st.session_state.sop_output = ""
if "sop_title" not in st.session_state:
    st.session_state.sop_title = ""
if "generated" not in st.session_state:
    st.session_state.generated = False


# ── UI ────────────────────────────────────────────────────────────────────────
st.markdown("""
<div class="sop-header">
    <div class="sop-badge">AI-Powered</div>
    <h1>📋 SOPilot</h1>
    <p>Describe any business process. Get a professional SOP document in seconds.</p>
</div>
""", unsafe_allow_html=True)

# ── Input Section ─────────────────────────────────────────────────────────────
st.markdown('<div class="section-label">Describe your business process</div>', unsafe_allow_html=True)
process_input = st.text_area(
    label="process",
    label_visibility="collapsed",
    placeholder="Example: Employee onboarding — from offer acceptance to end of first week. Includes IT setup, HR paperwork, team introductions, and initial training.",
    height=130
)

col1, col2 = st.columns(2)
with col1:
    st.markdown('<div class="section-label">Department</div>', unsafe_allow_html=True)
    department = st.selectbox(
        label="dept",
        label_visibility="collapsed",
        options=["HR", "Finance", "Operations", "IT", "Sales", "Other"]
    )
with col2:
    st.markdown('<div class="section-label">Complexity</div>', unsafe_allow_html=True)
    complexity = st.selectbox(
        label="complexity",
        label_visibility="collapsed",
        options=["Detailed", "Simple"]
    )

generate_btn = st.button("✨ Generate SOP", type="primary", use_container_width=True)

# ── Generate ──────────────────────────────────────────────────────────────────
if generate_btn:
    if not process_input.strip() or len(process_input.strip()) < 10:
        st.warning("Please describe your process in at least 10 characters.")
    else:
        with st.spinner("Generating your SOP..."):
            prompt = build_prompt(process_input, department, complexity)
            result = call_gemini(prompt)
            st.session_state.sop_output = result
            st.session_state.generated = True
            for line in result.split('\n'):
                if line.strip().startswith("TITLE:"):
                    st.session_state.sop_title = line.replace("TITLE:", "").strip()
                    break

# ── Output ────────────────────────────────────────────────────────────────────
if st.session_state.generated and st.session_state.sop_output:

    st.markdown('<div class="status-done">✅ SOP generated successfully</div>', unsafe_allow_html=True)
    st.markdown(f'<div class="sop-output">{st.session_state.sop_output}</div>', unsafe_allow_html=True)

    st.markdown("---")
    col_a, col_b = st.columns(2)

    with col_a:
        pdf_bytes = generate_pdf(st.session_state.sop_output, st.session_state.sop_title)
        st.download_button(
            label="📥 Download as PDF",
            data=pdf_bytes,
            file_name=f"SOP_{st.session_state.sop_title.replace(' ', '_')[:40]}_{datetime.now().strftime('%Y%m%d')}.pdf",
            mime="application/pdf",
            use_container_width=True
        )

    with col_b:
        st.download_button(
            label="📄 Download as TXT",
            data=st.session_state.sop_output,
            file_name=f"SOP_{datetime.now().strftime('%Y%m%d')}.txt",
            mime="text/plain",
            use_container_width=True
        )

    # ── Refinement Loop ───────────────────────────────────────────────────────
    st.markdown("### 🔄 Refine Your SOP")
    st.markdown("Not quite right? Give an instruction and regenerate.")

    refinement_input = st.text_input(
        label="refinement",
        label_visibility="collapsed",
        placeholder="e.g. Add a compliance section, make steps more detailed, include approval workflows..."
    )
    refine_btn = st.button("🔁 Apply Refinement", use_container_width=True)

    if refine_btn:
        if not refinement_input.strip():
            st.warning("Please enter a refinement instruction.")
        else:
            with st.spinner("Refining your SOP..."):
                refined_prompt = build_prompt(process_input, department, complexity, refinement_input)
                refined_result = call_gemini(refined_prompt)
                st.session_state.sop_output = refined_result
                for line in refined_result.split('\n'):
                    if line.strip().startswith("TITLE:"):
                        st.session_state.sop_title = line.replace("TITLE:", "").strip()
                        break
                st.rerun()